{application, bncsutils,
  [{description,  "bncsutils port"},
   {id,           "0"},
   {vsn,          "0"},
   {modules,      [bncs_app, bncs_sup, bncs_server]},
   {registered,   [bncs_sup, bncs_server]},
   {included_applications, []},
   {applications, [kernel, stdlib]},
   {env,          []},
   {mod,          {bncs_app, []}},
   {start_phases, []}]}.
